#ifndef BSP_HPP
#define BSP_HPP

#define BSP_RED_LED_PORT GPIOH
#define BSP_RED_LED_PIN 6

#define BSP_GREEN_LED_PORT GPIOH
#define BSP_GREEN_LED_PIN 7

#define BSP_USER_BUTTON_PORT GPIOC
#define BSP_USER_BUTTON_PIN 13

#endif
